DEFAULT_DATA_NAME = "mskchord"
DEFAULT_PRED_ENGINE = "gpt-5.6-sol_2026-07-09"
DEFAULT_MAX_TOKENS = 32000
DEFAULT_REASONING_EFFORT = "medium"

SURVPROMPT_DEFAULT_MODEL_LABEL = "SURV_PROB: GPT 5.6 Sol medium 0/None"
SURVPROMPT_HEADLINE_LABEL_CANDIDATES = (
    SURVPROMPT_DEFAULT_MODEL_LABEL,
    "SURV_PROB: GPT 5.6 Sol 0/None",
)
